### PR TITLE
Update of the softphone librairy to work with asterisk (Digest Auth updated)

### PR DESCRIPTION
**Pull request by pascal-pro**
Update the struct of Softphone and update the Digest Auth part to simplify use.
More info here: https://en.wikipedia.org/wiki/Digest_access_authentication

### CODE REVIEW

**Comment by Sean-Der** [comment]
Hey @pascal-ace 

Do you mind rebasing? Since you are behind master we have a bunch of conflicts.

How is the project going with these changes! Everything working, any bugs?

**Comment by pascal-ace** [comment]
I will try to make a separate branch, but normally, the conflicts are only in the SIP example, everything else is to refuse. (The hand has also changed its name)
This is a current update, to make it work with asterisk. For the moment, it still works with Freeswitch, but still not with asterisk. 
The softphone folder has been updated to add / change / clean up the library and make it more readable and clearer.

**Comment by pascal-ace** [comment]
Maybe you prefer that I host the softphone on my github, and that I make a version, so that the example always works, and I make you PR every time I change the lib or the structures?

**Comment by Sean-Der** [comment]
I am terribly sorry this didn't get merged. Not a great look to have PRs that get dropped for no reason :(

The good news is that Go now has an excellent SIP library! If anyone is working with SIP in Go I suggest using https://github.com/emiago/sipgo instead of implementing things yourselves. We have an example in-tree also.

**Pull request closed without merging**
